### ISSUE TITLE
La ricerca tramite le regexp [^] fallisce con più di un carattere

### ISSUE THREAD

**Issue by eathtespagheti** [andreademasi/apa#1]
Lascio un esempio per chiarezza

**stringa**: `are ere ire`
**regexp**: `[^ae]re`

**risultato corretto**: `ire`
**risultato ottenuto**: `Espressione non trovata.`

**Comment by andreademasi** [comment]
Dal testo del laboratorio ho inteso che può esserci al massimo un carattere in una regex del tipo [^x]

Il mar 5 nov 2019, 17:55 Fabi0Z <notifications@github.com> ha scritto:

**Comment by eathtespagheti** [comment]
> Dal testo del laboratorio ho inteso che può esserci al massimo un carattere in una regex del tipo [^x] Il mar 5 nov 2019, 17:55 Fabi0Z <notifications@github.com> ha scritto:
> […](#)

Nel testo dice

[^]  trova  ogni  singolo  carattere  non  contenuto  nelle  parentesi (cioè tutti i  caratteri  tra parentesi non vanno bene)

Quindi suppongo si intenda la possibilità che vi siano caratteri multipli
