### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GGmorello** [andreademasi/apa#2]
**Describe the bug**
Errore nell'esercizio 2 del lab 4, segna maggioritario -1 (assente)
**To Reproduce**
modificare il vettore preimpostato con {1, 1, 1, 2, 2, 2, 2, 2, 2, 1}
modificare le due dimensione pari a 8 con il valore 10
(compilato ed eseguito su repl)
**Expected behavior**
dovrebbe uscire 2 come maggioritario 

**Screenshots**

**Additional context**

**Comment by andreademasi** [comment]
@GGmorello ho fatto il refactoring della funzione, ora è anche più semplice rispetto a prima. Non ho testato la complessità però.
